namespace T4.Plugins.Troubadour;

public static class GetOutStore
{
    public static IEnumerable<ActorSnoId> ActorSnoIds { get; } = new List<ActorSnoId>
    {
        // spikes 1.3f
        ActorSnoId.DRLG_Trap_Spikes_2x2,
        ActorSnoId.DRLG_Trap_Spikes_3x3,
        // barrels 0.5f
        ActorSnoId.DRLG_Trap_Barrel_Cold_AOE,
        ActorSnoId.DRLG_Trap_Barrel_Fire_AOE,
        ActorSnoId.DRLG_Trap_Barrel_Lightning_AOE,
        ActorSnoId.DRLG_Trap_Barrel_Poison_AOE,
        ActorSnoId.DRLG_Trap_Barrel_Shadow_AOE,
        // traps 1f
        // ActorSnoId.DRLG_Trap_BearTrap,
        ActorSnoId.DRLG_Trap_BearTrap_DestroyableObject,
        ActorSnoId.DRLG_Trap_Moonseed,
        // mines 1f
        ActorSnoId.DRLG_Trap_Mine_Cold,
        ActorSnoId.DRLG_Trap_Mine_Fire,
        ActorSnoId.DRLG_Trap_Mine_Lightning,
        ActorSnoId.DRLG_Trap_Mine_Poison,
        ActorSnoId.DRLG_Trap_Mine_Shadow,
        // falls 1f
        ActorSnoId.DRLG_Trap_FallingRocks_FallingRocks,
        ActorSnoId.DRLG_Trap_FallingRocks_FallingRocksBrickDark,
        ActorSnoId.DRLG_Trap_FallingRocks_FallingRocksBrickDarkAndWood,
        ActorSnoId.DRLG_Trap_FallingRocks_FallingRocksBrickLight,
        ActorSnoId.DRLG_Trap_FallingRocks_FallingRocksSand,
        // dungeon affixes
        ActorSnoId.Dungeon_Affix_Orb,
        ActorSnoId.dungeon_affix_driftingShade_payload_burst_coasters,
        ActorSnoId.dungeon_affix_driftingShade_payload_persistent_ringMesh,
        ActorSnoId.dungeon_affix_driftingShade_projectile,
        ActorSnoId.dungeon_affix_driftingShade_projectile_coreMesh,
        ActorSnoId.dungeon_affix_driftingShade_projectile_parent,
        ActorSnoId.dungeon_affix_driftingShade_warning_coasters,
        //
        ActorSnoId.DRLG_Trap_Demonic,

    };

    public static IEnumerable<ActorSnoId> DebugActorSnoIds { get; } = new List<ActorSnoId>
    {
        // traps
        ActorSnoId.DRLG_Trap_Barrel_Cold_ClientEffect,
        ActorSnoId.DRLG_Trap_Barrel_Fire_ClientEffect,
        ActorSnoId.DRLG_Trap_Barrel_Lightning_ClientEffect,
        ActorSnoId.DRLG_Trap_Barrel_Poison_ClientEffect,
        ActorSnoId.DRLG_Trap_Barrel_Shadow_ClientEffect,
        ActorSnoId.DRLG_Trap_Bear_01_ClientEffect_Dyn,
        // ActorSnoId.DRLG_Trap_BearTrap,
        ActorSnoId.DRLG_Trap_BearTrap_BanditBoss,
        ActorSnoId.DRLG_Trap_Demonic_01_ClientEffect_Dyn,
        ActorSnoId.DRLG_Trap_Demonic_Projectile,
        // ActorSnoId.DRLG_Trap_FallingRocks_FallingRocks,
        // ActorSnoId.DRLG_Trap_FallingRocks_FallingRocksBrickDark,
        // ActorSnoId.DRLG_Trap_FallingRocks_FallingRocksBrickDarkAndWood,
        // ActorSnoId.DRLG_Trap_FallingRocks_FallingRocksBrickLight,
        // ActorSnoId.DRLG_Trap_FallingRocks_FallingRocksSand,
        ActorSnoId.DRLG_Trap_Frozen,
        ActorSnoId.DRLG_Trap_Frozen_ClientEffect_Dyn,
        ActorSnoId.DRLG_Trap_Frozen_Projectile,
        ActorSnoId.DRLG_Trap_Frozen_Projectile_Initial,
        ActorSnoId.DRLG_Trap_Generic_ElementalTotem_01_Cold_Stage01_Dyn,
        ActorSnoId.DRLG_Trap_Generic_ElementalTotem_01_Cold_Stage02_Dyn,
        ActorSnoId.DRLG_Trap_Generic_ElementalTotem_01_Fire_Stage01_Dyn,
        ActorSnoId.DRLG_Trap_Generic_ElementalTotem_01_Fire_Stage02_Dyn,
        ActorSnoId.DRLG_Trap_Generic_ElementalTotem_01_Lightning_Stage01_Dyn,
        ActorSnoId.DRLG_Trap_Generic_ElementalTotem_01_Lightning_Stage02_Dyn,
        ActorSnoId.DRLG_Trap_Generic_ElementalTotem_01_Poison_Stage01_Dyn,
        ActorSnoId.DRLG_Trap_Generic_ElementalTotem_01_Poison_Stage02_Dyn,
        ActorSnoId.DRLG_Trap_Generic_ElementalTotem_01_Shadow_Stage01_Dyn,
        ActorSnoId.DRLG_Trap_Generic_ElementalTotem_01_Shadow_Stage02_Dyn,
        ActorSnoId.DRLG_Trap_Geyser_Hell,
        ActorSnoId.DRLG_Trap_geyser_hell_deploy_bubble_mesh,
        ActorSnoId.DRLG_Trap_Geyser_Hell_Deploy_glowSphere,
        ActorSnoId.DRLG_Trap_Gloomspore,
        ActorSnoId.DRLG_Trap_Gloomspore_Base_ClientEffect_Dyn,
        ActorSnoId.DRLG_Trap_Gloomspore_Chunk_ClientEffect_Dyn,
        ActorSnoId.DRLG_Trap_Log,
        ActorSnoId.DRLG_Trap_Log_01_ClientEffect,
        ActorSnoId.DRLG_Trap_Log_DestroyableObject,
        // ActorSnoId.DRLG_Trap_Mine_Cold,
        // ActorSnoId.DRLG_Trap_Mine_Cold_SP,
        // ActorSnoId.DRLG_Trap_Mine_Death_Cold_ClientEffect_Dyn,
        // ActorSnoId.DRLG_Trap_Mine_Death_Fire_ClientEffect_Dyn,
        // ActorSnoId.DRLG_Trap_Mine_Death_Lightning_ClientEffect_Dyn,
        // ActorSnoId.DRLG_Trap_Mine_Death_Poison_ClientEffect_Dyn,
        // ActorSnoId.DRLG_Trap_Mine_Death_Shadow_ClientEffect_Dyn,
        // ActorSnoId.DRLG_Trap_Mine_Fire,
        // ActorSnoId.DRLG_Trap_Mine_Fire_SP,
        // ActorSnoId.DRLG_Trap_Mine_Lightning,
        // ActorSnoId.DRLG_Trap_Mine_Lightning_SP,
        // ActorSnoId.DRLG_Trap_Mine_Poison,
        // ActorSnoId.DRLG_Trap_Mine_Poison_SP,
        // ActorSnoId.DRLG_Trap_Mine_Shadow,
        // ActorSnoId.DRLG_Trap_Mine_Shadow_SP,
        // ActorSnoId.DRLG_Trap_Mine_Warning_Cold_ClientEffect_VFX,
        // ActorSnoId.DRLG_Trap_Mine_Warning_Poison_ClientEffect_VFX,
        // ActorSnoId.DRLG_Trap_Mine_Warning_Shadow_ClientEffect_VFX,
        ActorSnoId.DRLG_Trap_Spectral,
        ActorSnoId.DRLG_Trap_Spectral_01_ClientEffect_Dyn,
        ActorSnoId.DRLG_Trap_Spectral_Projectile,
        ActorSnoId.DRLG_Trap_Spectral_Projectile_First,
        ActorSnoId.DRLG_Trap_Totem_Fire,
        ActorSnoId.DRLG_Trap_Totem_Ice,
        ActorSnoId.DRLG_Trap_Totem_Lightning,
        ActorSnoId.DRLG_Trap_Totem_Poison,
        ActorSnoId.DRLG_Trap_Totem_Shadow,

        // affixes
        ActorSnoId.monsterAffix_chainPillar_base_chain,
        ActorSnoId.monsterAffix_Chaos_fumeRing,
        ActorSnoId.MonsterAffix_Chaos_WarningRing,
        ActorSnoId.MonsterAffix_ChillingWind_Wall,
        ActorSnoId.monsterAffix_electricLance_projectile_actor,
        ActorSnoId.monsterAffix_fireEnchanted_death_projectile,
        ActorSnoId.monsterAffix_FireEnchanted_flameTube,
        ActorSnoId.MonsterAffix_FireEnchanted_impact_glowsphere,
        ActorSnoId.monsterAffix_FireEnchanted_pjt,
        ActorSnoId.monsterAffix_FireEnchanted_pjt_leadingedge,
        ActorSnoId.MonsterAffix_FireEnchanted_Projectile,
        ActorSnoId.monsterAffix_fireEnchanted_warning_swirl,
        ActorSnoId.monsterAffix_fireEnchanted_wave_shell,
        ActorSnoId.monsterAffix_FireOrbs,
        ActorSnoId.MonsterAffix_FireOrbs_active,
        ActorSnoId.MonsterAffix_FireOrbs_Orb,
        ActorSnoId.monsterAffix_frozen_aoe_explosion_frostBuildupSphere,
        ActorSnoId.MonsterAffix_Frozen_Circle,
        ActorSnoId.monsterAffix_frozen_orb_mesh,
        ActorSnoId.monsterAffix_legendary_lightning_buildup_meshRoundBolt,
        ActorSnoId.monsterAffix_lightningEnchanted_projectile,
        ActorSnoId.monsterAffix_lightningEnchanted_trailActor,
        ActorSnoId.monsterAffix_lightningTotems_proj,
        ActorSnoId.monsterAffix_lightningTotems_projectile,
        ActorSnoId.MonsterAffix_LightningTotems_Totem,
        ActorSnoId.monsterAffix_mortar_aoe_explosion_FillSphere,
        ActorSnoId.monsterAffix_mortar_burstRing,
        ActorSnoId.monsterAffix_mortar_lobbed_attractor_child_proxy,
        ActorSnoId.monsterAffix_mortar_lobbed_attractor_parent_proxy,
        ActorSnoId.monsterAffix_mortar_projectile,
        ActorSnoId.monsterAffix_mortar_projectile_mesh,
        ActorSnoId.monsterAffix_mortar_warning_cyl,
        ActorSnoId.monsterAffix_plagueBearer_aoeExplosion_bubble,
        ActorSnoId.monsterAffix_plagueBearer_omni,
        ActorSnoId.MonsterAffix_PoisonEnchanted_Proxy,
        ActorSnoId.monsterAffix_poisonEnchantedoutwardMesh,
        ActorSnoId.monsterAffix_shadow_introSwirl,
        ActorSnoId.MonsterAffix_Summoner_Circle,
        ActorSnoId.MonsterAffix_Summoner_Circle_Small,
        ActorSnoId.monsterAffix_summoner_spawn_portal,
        ActorSnoId.monsterAffix_suppressor_barrier,
        ActorSnoId.monsterAffix_suppressor_parabola,
        ActorSnoId.monsterAffix_tether_chainBreak_links,
        ActorSnoId.MonsterAffix_Tether_Pillar,
        ActorSnoId.MonsterAffix_Tether_Pillar_01_Client_01_Dyn,
        ActorSnoId.MonsterAffix_Tether_Pillar_01_runeChains_ring,
        ActorSnoId.MonsterAffix_Tether_Pillar_AutoChain,
        ActorSnoId.monsterAffix_vampiricEnrage_powerUp,
        ActorSnoId.MonsterAffix_Vortex,
        ActorSnoId.monsterAffix_vortex_warning_icicle,
        ActorSnoId.monsterAffix_vortex_warning_icicle_fractured,
        // waller
        // ActorSnoId.MonsterAffix_Waller_damaged_Dyn,
        // ActorSnoId.MonsterAffix_Waller_Damaged_Multistage,
        // ActorSnoId.monsterAffix_waller_Impact_RockBreak,
        // ActorSnoId.MonsterAffix_Waller_rock_A_Dyn,
        // ActorSnoId.MonsterAffix_Waller_rock_B_Dyn,
        // ActorSnoId.MonsterAffix_Waller_rock_C_Dyn,
        // ActorSnoId.MonsterAffix_Waller_rock_E_Dyn,
        // ActorSnoId.MonsterAffix_Waller_rock_F_Dyn,
        // ActorSnoId.MonsterAffix_Waller_rock_G_Dyn,
        // ActorSnoId.MonsterAffix_Waller_rock_H_Dyn,
        // ActorSnoId.MonsterAffix_Waller_Untargetable_Wall,
        // ActorSnoId.MonsterAffix_Waller_Untargetable_Wall_Cannibal_Tyrant,
    };

    public static HashSet<ActorSnoId> DebugActorSnoIdSet { get; } = new(DebugActorSnoIds);
    public static HashSet<ActorSnoId> ActorSnoIdSet { get; } = new(ActorSnoIds);
}