// This file is auto-generated by Troubadour.Generator.AffixSnoIdsPublicWriter
// Do not edit this file manually or your changes will be lost when the file is regenerated.

// ReSharper disable All

namespace T4.Plugins.Troubadour;

public static partial class AffixSnoIds
{
    private static List<AffixSnoId> _generic { get; set; }
    public static List<AffixSnoId> Generic => _generic ??= new List<AffixSnoId>()
    {
        AffixSnoId.legendary_generic_006,
        AffixSnoId.legendary_generic_009,
        AffixSnoId.legendary_generic_011,
        AffixSnoId.legendary_generic_014,
        AffixSnoId.legendary_generic_016,
        AffixSnoId.legendary_generic_021,
        AffixSnoId.legendary_generic_027,
        AffixSnoId.legendary_generic_034,
        AffixSnoId.legendary_generic_036,
        AffixSnoId.legendary_generic_038,
        AffixSnoId.legendary_generic_043,
        AffixSnoId.legendary_generic_063,
        AffixSnoId.legendary_generic_065,
        AffixSnoId.legendary_generic_067,
        AffixSnoId.legendary_generic_100,
        AffixSnoId.legendary_generic_102,
        AffixSnoId.legendary_generic_103,
        AffixSnoId.legendary_generic_104,
        AffixSnoId.legendary_generic_106,
        AffixSnoId.legendary_generic_107,
        AffixSnoId.legendary_generic_109,
        AffixSnoId.Legendary_Generic_110,
        AffixSnoId.Legendary_Generic_111,
    };

    public static HashSet<AffixSnoId> GenericSet => _genericSet ??= new(Generic);
    private static HashSet<AffixSnoId> _genericSet { get; set; }

    private static List<AffixSnoId> _genericUnique { get; set; }
    public static List<AffixSnoId> GenericUnique => _genericUnique ??= new List<AffixSnoId>()
    {
        AffixSnoId._1HAxe_Unique_Generic_001,
        AffixSnoId._1HSword_Unique_Generic_001,
        AffixSnoId._2HSword_Unique_Generic_001,
        AffixSnoId.Amulet_Unique_Generic_100,
        AffixSnoId.Boots_Unique_Generic_001,
        AffixSnoId.Chest_Unique_Generic_100,
        AffixSnoId.Gloves_Unique_Generic_002,
        AffixSnoId.Gloves_Unique_Generic_003,
        AffixSnoId.Helm_Unique_Generic_001,
        AffixSnoId.Helm_Unique_Generic_002,
        AffixSnoId.Pants_Unique_Generic_100,
        AffixSnoId.Ring_Unique_Generic_100,
        AffixSnoId.Ring_Unique_Generic_101,
    };

    public static HashSet<AffixSnoId> GenericUniqueSet => _genericUniqueSet ??= new(GenericUnique);
    private static HashSet<AffixSnoId> _genericUniqueSet { get; set; }

    private static List<AffixSnoId> _barbarian { get; set; }
    public static List<AffixSnoId> Barbarian => _barbarian ??= new List<AffixSnoId>()
    {
        AffixSnoId.legendary_barb_001,
        AffixSnoId.legendary_barb_002,
        AffixSnoId.legendary_barb_003,
        AffixSnoId.legendary_barb_004,
        AffixSnoId.legendary_barb_005,
        AffixSnoId.legendary_barb_006,
        AffixSnoId.legendary_barb_007,
        AffixSnoId.legendary_barb_008,
        AffixSnoId.legendary_barb_010,
        AffixSnoId.legendary_barb_011,
        AffixSnoId.legendary_barb_013,
        AffixSnoId.legendary_barb_014,
        AffixSnoId.legendary_barb_017,
        AffixSnoId.legendary_barb_018,
        AffixSnoId.legendary_barb_019,
        AffixSnoId.legendary_barb_020,
        AffixSnoId.legendary_barb_021,
        AffixSnoId.legendary_barb_022,
        AffixSnoId.legendary_barb_023,
        AffixSnoId.legendary_barb_025,
        AffixSnoId.legendary_barb_026,
        AffixSnoId.legendary_barb_027,
        AffixSnoId.legendary_barb_040,
        AffixSnoId.legendary_barb_041,
        AffixSnoId.legendary_barb_050,
        AffixSnoId.legendary_barb_055,
        AffixSnoId.legendary_barb_057,
        AffixSnoId.legendary_barb_100,
        AffixSnoId.legendary_barb_102,
        AffixSnoId.legendary_barb_103,
        AffixSnoId.legendary_barb_104,
        AffixSnoId.legendary_barb_105,
        AffixSnoId.legendary_barb_106,
        AffixSnoId.legendary_barb_107,
        AffixSnoId.Legendary_Barb_108,
        AffixSnoId.Legendary_Barb_109,
        AffixSnoId.Legendary_Barb_110,
    };

    public static HashSet<AffixSnoId> BarbarianSet => _barbarianSet ??= new(Barbarian);
    private static HashSet<AffixSnoId> _barbarianSet { get; set; }

    private static List<AffixSnoId> _barbarianUnique { get; set; }
    public static List<AffixSnoId> BarbarianUnique => _barbarianUnique ??= new List<AffixSnoId>()
    {
        AffixSnoId._1HSword_Unique_Barb_101,
        AffixSnoId._2HAxe_Unique_Barb_001,
        AffixSnoId._2HMace_Unique_Barb_001,
        AffixSnoId._2HMace_Unique_Barb_100,
        AffixSnoId._2HSword_Unique_Barb_002,
        AffixSnoId.Amulet_Unique_Barb_100,
        AffixSnoId.Boots_Unique_Barb_100,
        AffixSnoId.Chest_Unique_Barb_100,
        AffixSnoId.Gloves_Unique_Barb_001,
    };

    public static HashSet<AffixSnoId> BarbarianUniqueSet => _barbarianUniqueSet ??= new(BarbarianUnique);
    private static HashSet<AffixSnoId> _barbarianUniqueSet { get; set; }

    private static List<AffixSnoId> _druid { get; set; }
    public static List<AffixSnoId> Druid => _druid ??= new List<AffixSnoId>()
    {
        AffixSnoId.legendary_druid_002,
        AffixSnoId.legendary_druid_005,
        AffixSnoId.legendary_druid_010,
        AffixSnoId.legendary_druid_013,
        AffixSnoId.legendary_druid_018,
        AffixSnoId.legendary_druid_023,
        AffixSnoId.legendary_druid_026,
        AffixSnoId.legendary_druid_028,
        AffixSnoId.legendary_druid_029,
        AffixSnoId.legendary_druid_038,
        AffixSnoId.legendary_druid_042,
        AffixSnoId.legendary_druid_047,
        AffixSnoId.legendary_druid_049,
        AffixSnoId.legendary_druid_059,
        AffixSnoId.legendary_druid_060,
        AffixSnoId.legendary_druid_062,
        AffixSnoId.legendary_druid_063,
        AffixSnoId.legendary_druid_066,
        AffixSnoId.legendary_druid_071,
        AffixSnoId.legendary_druid_074,
        AffixSnoId.legendary_druid_075,
        AffixSnoId.legendary_druid_077,
        AffixSnoId.legendary_druid_078,
        AffixSnoId.legendary_druid_080,
        AffixSnoId.legendary_druid_100,
        AffixSnoId.legendary_druid_102,
        AffixSnoId.legendary_druid_104,
        AffixSnoId.legendary_druid_106,
        AffixSnoId.legendary_druid_108,
        AffixSnoId.legendary_druid_109,
        AffixSnoId.legendary_druid_110,
        AffixSnoId.legendary_druid_111,
        AffixSnoId.legendary_druid_112,
        AffixSnoId.legendary_druid_113,
        AffixSnoId.legendary_druid_114,
        AffixSnoId.Legendary_Druid_115,
        AffixSnoId.Legendary_Druid_116,
        AffixSnoId.Legendary_Druid_117,
        AffixSnoId.Legendary_Druid_118,
        AffixSnoId.Legendary_Druid_119,
    };

    public static HashSet<AffixSnoId> DruidSet => _druidSet ??= new(Druid);
    private static HashSet<AffixSnoId> _druidSet { get; set; }

    private static List<AffixSnoId> _druidUnique { get; set; }
    public static List<AffixSnoId> DruidUnique => _druidUnique ??= new List<AffixSnoId>()
    {
        AffixSnoId._1HAxe_Unique_Druid_100,
        AffixSnoId._2HStaff_Unique_Druid_001,
        AffixSnoId.Chest_Unique_Druid_002,
        AffixSnoId.Chest_Unique_Druid_003,
        AffixSnoId.Helm_Unique_Druid_100,
        AffixSnoId.Helm_Unique_Druid_101,
        AffixSnoId.Pants_Unique_Druid_001,
        AffixSnoId.Ring_Unique_Druid_003,
    };

    public static HashSet<AffixSnoId> DruidUniqueSet => _druidUniqueSet ??= new(DruidUnique);
    private static HashSet<AffixSnoId> _druidUniqueSet { get; set; }

    private static List<AffixSnoId> _necromancer { get; set; }
    public static List<AffixSnoId> Necromancer => _necromancer ??= new List<AffixSnoId>()
    {
        AffixSnoId.legendary_necro_002,
        AffixSnoId.legendary_necro_003,
        AffixSnoId.legendary_necro_012,
        AffixSnoId.legendary_necro_016,
        AffixSnoId.legendary_necro_017,
        AffixSnoId.legendary_necro_020,
        AffixSnoId.legendary_necro_022,
        AffixSnoId.legendary_necro_023,
        AffixSnoId.legendary_necro_028,
        AffixSnoId.legendary_necro_029,
        AffixSnoId.legendary_necro_031,
        AffixSnoId.legendary_necro_032,
        AffixSnoId.legendary_necro_036,
        AffixSnoId.legendary_necro_038,
        AffixSnoId.legendary_necro_053,
        AffixSnoId.legendary_necro_054,
        AffixSnoId.legendary_necro_066,
        AffixSnoId.legendary_necro_067,
        AffixSnoId.legendary_necro_100,
        AffixSnoId.legendary_necro_101,
        AffixSnoId.legendary_necro_102,
        AffixSnoId.legendary_necro_103,
        AffixSnoId.legendary_necro_104,
        AffixSnoId.legendary_necro_105,
        AffixSnoId.legendary_necro_106,
        AffixSnoId.legendary_necro_107,
        AffixSnoId.legendary_necro_108,
        AffixSnoId.legendary_necro_109,
        AffixSnoId.legendary_necro_110,
        AffixSnoId.legendary_necro_111,
        AffixSnoId.legendary_necro_112,
        AffixSnoId.legendary_necro_113,
        AffixSnoId.legendary_necro_114,
        AffixSnoId.legendary_necro_115,
        AffixSnoId.legendary_necro_116,
        AffixSnoId.legendary_necro_117,
        AffixSnoId.legendary_necro_118,
        AffixSnoId.legendary_necro_119,
        AffixSnoId.legendary_necro_120,
        AffixSnoId.Legendary_Necro_121,
        AffixSnoId.Legendary_Necro_122,
    };

    public static HashSet<AffixSnoId> NecromancerSet => _necromancerSet ??= new(Necromancer);
    private static HashSet<AffixSnoId> _necromancerSet { get; set; }

    private static List<AffixSnoId> _necromancerUnique { get; set; }
    public static List<AffixSnoId> NecromancerUnique => _necromancerUnique ??= new List<AffixSnoId>()
    {
        AffixSnoId._1HScythe_Unique_Necro_100,
        AffixSnoId._2HScythe_Unique_Necro_100,
        AffixSnoId.Amulet_Unique_Necro_100,
        AffixSnoId.Boots_Unique_Necro_100,
        AffixSnoId.Chest_Unique_Necro_101,
        AffixSnoId.Gloves_Unique_Necro_100,
        AffixSnoId.Helm_Unique_Necro_100,
        AffixSnoId.Ring_Unique_Necro_100,
    };

    public static HashSet<AffixSnoId> NecromancerUniqueSet => _necromancerUniqueSet ??= new(NecromancerUnique);
    private static HashSet<AffixSnoId> _necromancerUniqueSet { get; set; }

    private static List<AffixSnoId> _rogue { get; set; }
    public static List<AffixSnoId> Rogue => _rogue ??= new List<AffixSnoId>()
    {
        AffixSnoId.legendary_rogue_003,
        AffixSnoId.legendary_rogue_004,
        AffixSnoId.legendary_rogue_010,
        AffixSnoId.legendary_rogue_011,
        AffixSnoId.legendary_rogue_013,
        AffixSnoId.legendary_rogue_014,
        AffixSnoId.legendary_rogue_018,
        AffixSnoId.legendary_rogue_019,
        AffixSnoId.legendary_rogue_020,
        AffixSnoId.legendary_rogue_021,
        AffixSnoId.legendary_rogue_023,
        AffixSnoId.legendary_rogue_024,
        AffixSnoId.legendary_rogue_026,
        AffixSnoId.legendary_rogue_028,
        AffixSnoId.legendary_rogue_029,
        AffixSnoId.legendary_rogue_100,
        AffixSnoId.legendary_rogue_101,
        AffixSnoId.legendary_rogue_102,
        AffixSnoId.legendary_rogue_103,
        AffixSnoId.legendary_rogue_104,
        AffixSnoId.legendary_rogue_105,
        AffixSnoId.legendary_rogue_106,
        AffixSnoId.legendary_rogue_107,
        AffixSnoId.legendary_rogue_108,
        AffixSnoId.legendary_rogue_109,
        AffixSnoId.legendary_rogue_110,
        AffixSnoId.legendary_rogue_111,
        AffixSnoId.legendary_rogue_112,
        AffixSnoId.legendary_rogue_113,
        AffixSnoId.legendary_rogue_114,
        AffixSnoId.legendary_rogue_116,
        AffixSnoId.legendary_rogue_117,
        AffixSnoId.legendary_rogue_118,
        AffixSnoId.legendary_rogue_119,
        AffixSnoId.legendary_rogue_120,
        AffixSnoId.legendary_rogue_121,
        AffixSnoId.legendary_rogue_122,
        AffixSnoId.legendary_rogue_123,
        AffixSnoId.Legendary_Rogue_124,
        AffixSnoId.Legendary_Rogue_125,
    };

    public static HashSet<AffixSnoId> RogueSet => _rogueSet ??= new(Rogue);
    private static HashSet<AffixSnoId> _rogueSet { get; set; }

    private static List<AffixSnoId> _rogueUnique { get; set; }
    public static List<AffixSnoId> RogueUnique => _rogueUnique ??= new List<AffixSnoId>()
    {
        AffixSnoId._1HDagger_Unique_Rogue_001,
        AffixSnoId._1HDagger_Unique_Rogue_002,
        AffixSnoId._2HBow_Unique_Rogue_001,
        AffixSnoId._2HBow_Unique_Rogue_006,
        AffixSnoId.Amulet_Unique_Rogue_100,
        AffixSnoId.Gloves_Unique_Rogue_100,
        AffixSnoId.Helm_Unique_Rogue_001,
        AffixSnoId.Pants_Unique_Rogue_004,
    };

    public static HashSet<AffixSnoId> RogueUniqueSet => _rogueUniqueSet ??= new(RogueUnique);
    private static HashSet<AffixSnoId> _rogueUniqueSet { get; set; }

    private static List<AffixSnoId> _sorcerer { get; set; }
    public static List<AffixSnoId> Sorcerer => _sorcerer ??= new List<AffixSnoId>()
    {
        AffixSnoId.legendary_sorc_004,
        AffixSnoId.legendary_sorc_006,
        AffixSnoId.legendary_sorc_008,
        AffixSnoId.legendary_sorc_012,
        AffixSnoId.legendary_sorc_017,
        AffixSnoId.legendary_sorc_027,
        AffixSnoId.legendary_sorc_035,
        AffixSnoId.legendary_sorc_039,
        AffixSnoId.legendary_sorc_043,
        AffixSnoId.legendary_sorc_100,
        AffixSnoId.legendary_sorc_101,
        AffixSnoId.legendary_sorc_102,
        AffixSnoId.legendary_sorc_103,
        AffixSnoId.legendary_sorc_104,
        AffixSnoId.legendary_sorc_105,
        AffixSnoId.legendary_sorc_106,
        AffixSnoId.legendary_sorc_107,
        AffixSnoId.legendary_sorc_108,
        AffixSnoId.legendary_sorc_109,
        AffixSnoId.legendary_sorc_110,
        AffixSnoId.legendary_sorc_111,
        AffixSnoId.legendary_sorc_112,
        AffixSnoId.legendary_sorc_113,
        AffixSnoId.legendary_sorc_115,
        AffixSnoId.legendary_sorc_116,
        AffixSnoId.legendary_sorc_117,
        AffixSnoId.legendary_sorc_118,
        AffixSnoId.legendary_sorc_119,
        AffixSnoId.legendary_sorc_120,
        AffixSnoId.legendary_sorc_121,
        AffixSnoId.legendary_sorc_122,
        AffixSnoId.legendary_sorc_123,
        AffixSnoId.legendary_sorc_124,
        AffixSnoId.legendary_sorc_125,
        AffixSnoId.legendary_sorc_126,
        AffixSnoId.legendary_sorc_127,
        AffixSnoId.legendary_sorc_128,
        AffixSnoId.legendary_sorc_129,
        AffixSnoId.legendary_sorc_131,
        AffixSnoId.legendary_sorc_132,
        AffixSnoId.Legendary_Sorc_133,
        AffixSnoId.Legendary_Sorc_134,
        AffixSnoId.Legendary_Sorc_135,
    };

    public static HashSet<AffixSnoId> SorcererSet => _sorcererSet ??= new(Sorcerer);
    private static HashSet<AffixSnoId> _sorcererSet { get; set; }

    private static List<AffixSnoId> _sorcererUnique { get; set; }
    public static List<AffixSnoId> SorcererUnique => _sorcererUnique ??= new List<AffixSnoId>()
    {
        AffixSnoId._1HWand_Unique_Sorc_100,
        AffixSnoId._2HStaff_Unique_Sorc_002,
        AffixSnoId._2HStaff_Unique_Sorc_100,
        AffixSnoId.Amulet_Unique_Sorc_100,
        AffixSnoId.Boots_Unique_Sorc_100,
        AffixSnoId.Chest_Unique_Sorc_002,
        AffixSnoId.Gloves_Unique_Sorc_002,
        AffixSnoId.Pants_Unique_Sorc_100,
    };

    public static HashSet<AffixSnoId> SorcererUniqueSet => _sorcererUniqueSet ??= new(SorcererUnique);
    private static HashSet<AffixSnoId> _sorcererUniqueSet { get; set; }

    public static bool TryGetUniqueItemSnoId(this AffixSnoId snoId, out ItemSnoId itemSnoId)
    {
        itemSnoId = snoId switch
        {
            AffixSnoId._1HAxe_Unique_Druid_100 => ItemSnoId._1HAxe_Unique_Druid_100,
            AffixSnoId._1HAxe_Unique_Generic_001 => ItemSnoId._1HAxe_Unique_Generic_001,
            AffixSnoId._1HDagger_Unique_Rogue_001 => ItemSnoId._1HDagger_Unique_Rogue_001,
            AffixSnoId._1HDagger_Unique_Rogue_002 => ItemSnoId._1HDagger_Unique_Rogue_002,
            AffixSnoId._1HScythe_Unique_Necro_100 => ItemSnoId._1HScythe_Unique_Necro_100,
            AffixSnoId._1HSword_Unique_Barb_101 => ItemSnoId._1HSword_Unique_Barb_101,
            AffixSnoId._1HSword_Unique_Generic_001 => ItemSnoId._1HSword_Unique_Generic_001,
            AffixSnoId._1HWand_Unique_Sorc_100 => ItemSnoId._1HWand_Unique_Sorc_100,
            AffixSnoId._2HAxe_Unique_Barb_001 => ItemSnoId._2HAxe_Unique_Barb_001,
            AffixSnoId._2HBow_Unique_Rogue_001 => ItemSnoId._2HBow_Unique_Rogue_001,
            AffixSnoId._2HBow_Unique_Rogue_006 => ItemSnoId._2HBow_Unique_Rogue_006,
            AffixSnoId._2HMace_Unique_Barb_001 => ItemSnoId._2HMace_Unique_Barb_001,
            AffixSnoId._2HMace_Unique_Barb_100 => ItemSnoId._2HMace_Unique_Barb_100,
            AffixSnoId._2HScythe_Unique_Necro_100 => ItemSnoId._2HScythe_Unique_Necro_100,
            AffixSnoId._2HStaff_Unique_Druid_001 => ItemSnoId._2HStaff_Unique_Druid_001,
            AffixSnoId._2HStaff_Unique_Sorc_002 => ItemSnoId._2HStaff_Unique_Sorc_002,
            AffixSnoId._2HStaff_Unique_Sorc_100 => ItemSnoId._2HStaff_Unique_Sorc_100,
            AffixSnoId._2HSword_Unique_Barb_002 => ItemSnoId._2HSword_Unique_Barb_002,
            AffixSnoId._2HSword_Unique_Generic_001 => ItemSnoId._2HSword_Unique_Generic_001,
            AffixSnoId.Amulet_Unique_Barb_100 => ItemSnoId.Amulet_Unique_Barb_100,
            AffixSnoId.Amulet_Unique_Generic_100 => ItemSnoId.Amulet_Unique_Generic_100,
            AffixSnoId.Amulet_Unique_Necro_100 => ItemSnoId.Amulet_Unique_Necro_100,
            AffixSnoId.Amulet_Unique_Rogue_100 => ItemSnoId.Amulet_Unique_Rogue_100,
            AffixSnoId.Amulet_Unique_Sorc_100 => ItemSnoId.Amulet_Unique_Sorc_100,
            AffixSnoId.Boots_Unique_Barb_100 => ItemSnoId.Boots_Unique_Barb_100,
            AffixSnoId.Boots_Unique_Generic_001 => ItemSnoId.Boots_Unique_Generic_001,
            AffixSnoId.Boots_Unique_Necro_100 => ItemSnoId.Boots_Unique_Necro_100,
            AffixSnoId.Boots_Unique_Sorc_100 => ItemSnoId.Boots_Unique_Sorc_100,
            AffixSnoId.Chest_Unique_Barb_100 => ItemSnoId.Chest_Unique_Barb_100,
            AffixSnoId.Chest_Unique_Druid_002 => ItemSnoId.Chest_Unique_Druid_002,
            AffixSnoId.Chest_Unique_Druid_003 => ItemSnoId.Chest_Unique_Druid_003,
            AffixSnoId.Chest_Unique_Generic_100 => ItemSnoId.Chest_Unique_Generic_100,
            AffixSnoId.Chest_Unique_Necro_101 => ItemSnoId.Chest_Unique_Necro_101,
            AffixSnoId.Chest_Unique_Sorc_002 => ItemSnoId.Chest_Unique_Sorc_002,
            AffixSnoId.Gloves_Unique_Barb_001 => ItemSnoId.Gloves_Unique_Barb_001,
            AffixSnoId.Gloves_Unique_Generic_002 => ItemSnoId.Gloves_Unique_Generic_002,
            AffixSnoId.Gloves_Unique_Generic_003 => ItemSnoId.Gloves_Unique_Generic_003,
            AffixSnoId.Gloves_Unique_Necro_100 => ItemSnoId.Gloves_Unique_Necro_100,
            AffixSnoId.Gloves_Unique_Rogue_100 => ItemSnoId.Gloves_Unique_Rogue_100,
            AffixSnoId.Gloves_Unique_Sorc_002 => ItemSnoId.Gloves_Unique_Sorc_002,
            AffixSnoId.Helm_Unique_Druid_100 => ItemSnoId.Helm_Unique_Druid_100,
            AffixSnoId.Helm_Unique_Druid_101 => ItemSnoId.Helm_Unique_Druid_101,
            AffixSnoId.Helm_Unique_Generic_001 => ItemSnoId.Helm_Unique_Generic_001,
            AffixSnoId.Helm_Unique_Generic_002 => ItemSnoId.Helm_Unique_Generic_002,
            AffixSnoId.Helm_Unique_Necro_100 => ItemSnoId.Helm_Unique_Necro_100,
            AffixSnoId.Helm_Unique_Rogue_001 => ItemSnoId.Helm_Unique_Rogue_001,
            AffixSnoId.Pants_Unique_Druid_001 => ItemSnoId.Pants_Unique_Druid_001,
            AffixSnoId.Pants_Unique_Generic_100 => ItemSnoId.Pants_Unique_Generic_100,
            AffixSnoId.Pants_Unique_Rogue_004 => ItemSnoId.Pants_Unique_Rogue_004,
            AffixSnoId.Pants_Unique_Sorc_100 => ItemSnoId.Pants_Unique_Sorc_100,
            AffixSnoId.Ring_Unique_Druid_003 => ItemSnoId.Ring_Unique_Druid_003,
            AffixSnoId.Ring_Unique_Generic_100 => ItemSnoId.Ring_Unique_Generic_100,
            AffixSnoId.Ring_Unique_Generic_101 => ItemSnoId.Ring_Unique_Generic_101,
            AffixSnoId.Ring_Unique_Necro_100 => ItemSnoId.Ring_Unique_Necro_100,
            _ => ItemSnoId.Axe__Bad__Data,
        };

        return itemSnoId != ItemSnoId.Axe__Bad__Data;
    }

    public static bool TryGetUniqueAffixSnoId(this ItemSnoId itemSnoId, out AffixSnoId snoId)
    {
        snoId = itemSnoId switch
        {
            ItemSnoId._1HAxe_Unique_Druid_100 => AffixSnoId._1HAxe_Unique_Druid_100,
            ItemSnoId._1HAxe_Unique_Generic_001 => AffixSnoId._1HAxe_Unique_Generic_001,
            ItemSnoId._1HDagger_Unique_Rogue_001 => AffixSnoId._1HDagger_Unique_Rogue_001,
            ItemSnoId._1HDagger_Unique_Rogue_002 => AffixSnoId._1HDagger_Unique_Rogue_002,
            ItemSnoId._1HScythe_Unique_Necro_100 => AffixSnoId._1HScythe_Unique_Necro_100,
            ItemSnoId._1HSword_Unique_Barb_101 => AffixSnoId._1HSword_Unique_Barb_101,
            ItemSnoId._1HSword_Unique_Generic_001 => AffixSnoId._1HSword_Unique_Generic_001,
            ItemSnoId._1HWand_Unique_Sorc_100 => AffixSnoId._1HWand_Unique_Sorc_100,
            ItemSnoId._2HAxe_Unique_Barb_001 => AffixSnoId._2HAxe_Unique_Barb_001,
            ItemSnoId._2HBow_Unique_Rogue_001 => AffixSnoId._2HBow_Unique_Rogue_001,
            ItemSnoId._2HBow_Unique_Rogue_006 => AffixSnoId._2HBow_Unique_Rogue_006,
            ItemSnoId._2HMace_Unique_Barb_001 => AffixSnoId._2HMace_Unique_Barb_001,
            ItemSnoId._2HMace_Unique_Barb_100 => AffixSnoId._2HMace_Unique_Barb_100,
            ItemSnoId._2HScythe_Unique_Necro_100 => AffixSnoId._2HScythe_Unique_Necro_100,
            ItemSnoId._2HStaff_Unique_Druid_001 => AffixSnoId._2HStaff_Unique_Druid_001,
            ItemSnoId._2HStaff_Unique_Sorc_002 => AffixSnoId._2HStaff_Unique_Sorc_002,
            ItemSnoId._2HStaff_Unique_Sorc_100 => AffixSnoId._2HStaff_Unique_Sorc_100,
            ItemSnoId._2HSword_Unique_Barb_002 => AffixSnoId._2HSword_Unique_Barb_002,
            ItemSnoId._2HSword_Unique_Generic_001 => AffixSnoId._2HSword_Unique_Generic_001,
            ItemSnoId.Amulet_Unique_Barb_100 => AffixSnoId.Amulet_Unique_Barb_100,
            ItemSnoId.Amulet_Unique_Generic_100 => AffixSnoId.Amulet_Unique_Generic_100,
            ItemSnoId.Amulet_Unique_Necro_100 => AffixSnoId.Amulet_Unique_Necro_100,
            ItemSnoId.Amulet_Unique_Rogue_100 => AffixSnoId.Amulet_Unique_Rogue_100,
            ItemSnoId.Amulet_Unique_Sorc_100 => AffixSnoId.Amulet_Unique_Sorc_100,
            ItemSnoId.Boots_Unique_Barb_100 => AffixSnoId.Boots_Unique_Barb_100,
            ItemSnoId.Boots_Unique_Generic_001 => AffixSnoId.Boots_Unique_Generic_001,
            ItemSnoId.Boots_Unique_Necro_100 => AffixSnoId.Boots_Unique_Necro_100,
            ItemSnoId.Boots_Unique_Sorc_100 => AffixSnoId.Boots_Unique_Sorc_100,
            ItemSnoId.Chest_Unique_Barb_100 => AffixSnoId.Chest_Unique_Barb_100,
            ItemSnoId.Chest_Unique_Druid_002 => AffixSnoId.Chest_Unique_Druid_002,
            ItemSnoId.Chest_Unique_Druid_003 => AffixSnoId.Chest_Unique_Druid_003,
            ItemSnoId.Chest_Unique_Generic_100 => AffixSnoId.Chest_Unique_Generic_100,
            ItemSnoId.Chest_Unique_Necro_101 => AffixSnoId.Chest_Unique_Necro_101,
            ItemSnoId.Chest_Unique_Sorc_002 => AffixSnoId.Chest_Unique_Sorc_002,
            ItemSnoId.Gloves_Unique_Barb_001 => AffixSnoId.Gloves_Unique_Barb_001,
            ItemSnoId.Gloves_Unique_Generic_002 => AffixSnoId.Gloves_Unique_Generic_002,
            ItemSnoId.Gloves_Unique_Generic_003 => AffixSnoId.Gloves_Unique_Generic_003,
            ItemSnoId.Gloves_Unique_Necro_100 => AffixSnoId.Gloves_Unique_Necro_100,
            ItemSnoId.Gloves_Unique_Rogue_100 => AffixSnoId.Gloves_Unique_Rogue_100,
            ItemSnoId.Gloves_Unique_Sorc_002 => AffixSnoId.Gloves_Unique_Sorc_002,
            ItemSnoId.Helm_Unique_Druid_100 => AffixSnoId.Helm_Unique_Druid_100,
            ItemSnoId.Helm_Unique_Druid_101 => AffixSnoId.Helm_Unique_Druid_101,
            ItemSnoId.Helm_Unique_Generic_001 => AffixSnoId.Helm_Unique_Generic_001,
            ItemSnoId.Helm_Unique_Generic_002 => AffixSnoId.Helm_Unique_Generic_002,
            ItemSnoId.Helm_Unique_Necro_100 => AffixSnoId.Helm_Unique_Necro_100,
            ItemSnoId.Helm_Unique_Rogue_001 => AffixSnoId.Helm_Unique_Rogue_001,
            ItemSnoId.Pants_Unique_Druid_001 => AffixSnoId.Pants_Unique_Druid_001,
            ItemSnoId.Pants_Unique_Generic_100 => AffixSnoId.Pants_Unique_Generic_100,
            ItemSnoId.Pants_Unique_Rogue_004 => AffixSnoId.Pants_Unique_Rogue_004,
            ItemSnoId.Pants_Unique_Sorc_100 => AffixSnoId.Pants_Unique_Sorc_100,
            ItemSnoId.Ring_Unique_Druid_003 => AffixSnoId.Ring_Unique_Druid_003,
            ItemSnoId.Ring_Unique_Generic_100 => AffixSnoId.Ring_Unique_Generic_100,
            ItemSnoId.Ring_Unique_Generic_101 => AffixSnoId.Ring_Unique_Generic_101,
            ItemSnoId.Ring_Unique_Necro_100 => AffixSnoId.Ring_Unique_Necro_100,
            _ => AffixSnoId.Axe__Bad__Data,
        };

        return itemSnoId != ItemSnoId.Axe__Bad__Data;
    }
}
